---
- name: copy open_firewall_port.sh.j2 template across
  become: yes
  template:
    src: "open_firewall_port.sh.j2"
    dest: "{{ hostvars[inventory_hostname].home_dir }}/open_firewall_port.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: run iptables command
  become: yes
  shell: "{{ hostvars[inventory_hostname].home_dir }}/open_firewall_port.sh"
