---
- name: install gnutils-bin
  become: yes
  apt:
    name: gnutls-bin
    state: latest

######## LDAP ########

- name: Secure ldap.conf
  become: yes
  file:
    path: /etc/ldap.conf
    mode: 0700

- name: configure /etc/nslcd.conf
  become: yes
  lineinfile:  
    path: /etc/nslcd.conf
    state: present
    regexp: 'uri ldap.*/'
    line: "uri ldaps://{{ hostvars[inventory_hostname].server }}:636/"

- name: configure /etc/nslcd.conf
  become: yes
  lineinfile:  
    path: /etc/nslcd.conf
    state: present
    regexp: '#ssl.* '
    line: "ssl on"

- name: configure /etc/nslcd.conf
  become: yes
  lineinfile:  
    path: /etc/nslcd.conf
    state: present
    regexp: 'tls_reqcert allow'
    line: "tls_reqcert allow"

- name: configure /etc/ldap/ldap.conf
  become: yes
  lineinfile:  
    path: /etc/ldap/ldap.conf
    state: present
    regexp: '(?i)URI ldap.*'
    line: "URI ldaps://{{ hostvars[inventory_hostname].server }}:636/"

- name: configure /etc/ldap/ldap.conf
  become: yes
  lineinfile:  
    path: /etc/ldap/ldap.conf
    state: present
    regexp: 'TLS_REQCERT allow'
    line: "TLS_REQCERT allow"

- name: configure /etc/ldap.conf
  become: yes
  lineinfile:  
    path: /etc/ldap.conf
    state: present
    regexp: '(?i)URI ldap.*'
    line: "URI ldaps://{{ hostvars[inventory_hostname].server }}:636/"

- name: configure /etc/ldap.conf
  become: yes
  lineinfile:  
    path: /etc/ldap.conf
    state: present
    regexp: 'TLS_REQCERT allow'
    line: "TLS_REQCERT allow"
    
### Restart everything

#- name: check autofs on
#  become: yes
#  shell: chkconfig autofs on

- name: enable nscd
  become: yes
  service:
    name: nscd
    enabled: yes
    state:  restarted

- name: enable autofs
  become: yes
  service:
    name: autofs
    enabled: yes
    state:  restarted

- name: enable nslcd
  become: yes
  service:
    name: nslcd
    enabled: yes
    state:  restarted

- name: enable slapd
  become: yes
  service:
    name: slapd
    enabled: yes
    state:  restarted
