---
- name: Create target directory
  become: yes
  file:
    path: "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}"
    state: directory
    mode: 0755
    
- name: Copy authorized_keys to VM
  become: yes
  copy:  
    src: "../../../../../docker/{{ hostvars[inventory_hostname].os_name }}/authorized_keys"
    dest: "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/authorized_keys"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy docker_bootstrap_script.sh to VM
  become: yes
  copy:  
    src: "../../../../../docker/{{ hostvars[inventory_hostname].os_name }}/docker_bootstrap_script.sh"
    dest: "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/docker_bootstrap_script.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy docker_build.sh to VM
  become: yes
  copy:  
    src: "../../../../../docker/{{ hostvars[inventory_hostname].os_name }}/docker_build.sh"
    dest: "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/docker_build.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    
- name: Copy dockerfile to VM
  become: yes
  copy:  
    src: "../../../../../docker/{{ hostvars[inventory_hostname].os_name }}/dockerfile"
    dest: "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/dockerfile"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy docker_run.sh to VM
  become: yes
  copy:  
    src: "../../../../../docker/{{ hostvars[inventory_hostname].os_name }}/docker_run.sh"
    dest: "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/docker_run.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    
- name: Copy myOverrides to VM
  become: yes
  copy:  
    src: "../../../../../docker/{{ hostvars[inventory_hostname].os_name }}/myOverrides"
    dest: "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/myOverrides"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
##########################################################################################################
- name: Run docker build
  become: yes
  shell:  ./docker_build.sh
  args:
    chdir:  "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/"
    
- name: Run docker run command
  become: yes
  shell:  ./docker_run.sh
  args:
    chdir:  "{{ hostvars[inventory_hostname].home_dir }}/{{ hostvars[inventory_hostname].vm_name }}/{{ hostvars[inventory_hostname].container_name }}/"
