---
- hosts:
  - masters
  remote_user: "{{ hostvars[inventory_hostname].username }}"
  roles:   
    - { role: 'logstash_centos', when:  "hostvars[inventory_hostname].os_name == 'centos'" }
    - { role: 'logstash_ubuntu', when:  "hostvars[inventory_hostname].os_name == 'ubuntu'" }    
