---
-   hosts:
    - masters
    remote_user: "{{ hostvars[inventory_hostname].username }}"
    roles:
      - { role: 'configure_dns_centos', when:  "hostvars[inventory_hostname].os_name == 'centos'" }
      - { role: 'configure_dns_ubuntu', when:  "hostvars[inventory_hostname].os_name == 'ubuntu'" }
